name: Azure Bicep
  
on:
  workflow_dispatch

  # Environment variables are defined in an "env" section.
  # We set the target environment to dev.
  # Open the deploy-advanced.yml file to see how we can accept user input
  # instead of needing to change this file to switch environments.
env:
  targetEnv: dev
  # The overall workflow name will be Azure Bicep. This will show up in the
  # GitHub Action page.

jobs:
    # This script has one job: build and deploy the IaC resources
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Azure client ID stored in secrets
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Azure tenant ID stored in secrets
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure subscription ID stored in secrets
        federated-token: ${{ secrets.AZURE_FEDERATED_TOKEN }}  # Azure federated token stored in secrets
        enable-AzPSSession: true

        # Deploy ARM template
    - name: Run ARM deploy
        # https://github.com/azure/arm-deploy
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup  # Scope of the deployment is a resource group
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure subscription ID stored in secrets
        template: ./src/InfrastructureAsCode/main.bicep  # Path to the Bicep template file
        parameters: environment=${{ env.targetEnv }}  # Parameters for the template with environment value